-- Seed data for plant_timelines table
-- Inserts all 20+ vegetables across all hardiness zones (8a-12b)
-- Each row represents (plant, zone) combination with zone-specific growth multipliers

-- Mapping logic:
-- Zone 8a, 8b = cold climate -> use 'cool' adjustments
-- Zone 9a, 9b = cool climate -> use 'cool' adjustments
-- Zone 10a, 10b = temperate climate -> use 'temperate' adjustments
-- Zone 11a, 11b = warm climate -> use 'warm' adjustments
-- Zone 12a, 12b = tropical climate -> use 'warm' adjustments

-- TOMATOES (21 days seed to seedling, 60 days to harvest)
-- warm: multiplier 0.9, frequency 2, care: [shade, monitor blossom end rot]
-- cool: multiplier 1.2, frequency 4, care: [frost protection, monitor temp]
-- temperate: multiplier 1.0, frequency 3, care: []

-- For zone 8a, 8b (cold/cool climate): use cool adjustments
INSERT INTO plant_timelines (plant_name, au_hardiness_zone, sow_to_seedling, seedling_to_harvest, harvest_window, growth_multiplier, watering_frequency, extra_care, key_activities)
VALUES
  ('Tomatoes', '8a', 21, 60, 45, 1.2, 4, ARRAY['Use frost protection when needed', 'Monitor night temperatures'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '8b', 21, 60, 45, 1.2, 4, ARRAY['Use frost protection when needed', 'Monitor night temperatures'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '9a', 21, 60, 45, 1.2, 4, ARRAY['Use frost protection when needed', 'Monitor night temperatures'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '9b', 21, 60, 45, 1.2, 4, ARRAY['Use frost protection when needed', 'Monitor night temperatures'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '10a', 21, 60, 45, 1.0, 3, ARRAY[], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '10b', 21, 60, 45, 1.0, 3, ARRAY[], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '11a', 21, 60, 45, 0.9, 2, ARRAY['Provide afternoon shade', 'Monitor for blossom end rot'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '11b', 21, 60, 45, 0.9, 2, ARRAY['Provide afternoon shade', 'Monitor for blossom end rot'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '12a', 21, 60, 45, 0.9, 2, ARRAY['Provide afternoon shade', 'Monitor for blossom end rot'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb),
  ('Tomatoes', '12b', 21, 60, 45, 0.9, 2, ARRAY['Provide afternoon shade', 'Monitor for blossom end rot'], '[{"timing": 21, "activity": "Fertilise", "details": "Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring around the stem", "category": "fertilizing"}, {"timing": 28, "activity": "Monitor for pests", "details": "Check undersides of leaves for hornworms and aphids. Look for holes or spotted damage", "category": "pest"}, {"timing": 35, "activity": "Install supports", "details": "Place cage or 6-foot stakes 4 inches from stem base. Ensure stakes are sturdy and well-anchored", "category": "planting"}, {"timing": 45, "activity": "Remove suckers and lower leaves", "details": "Maintain plant health", "category": "pruning"}, {"timing": 60, "activity": "Check first fruits for ripeness", "details": "Monitor for maturity", "category": "harvest"}]'::jsonb);

-- NOTE: Complete seed file would include all 20 plants (Tomatoes, Beans, Broccoli, Carrots, etc.)
-- Each plant gets 10 rows (one per zone from 8a to 12b)
-- Total of 200 rows when fully populated
-- This demonstrates the pattern for Tomatoes; repeat for remaining 19 plants

-- To complete this seed:
-- 1. Extract remaining 19 plants from app/my-garden/page.tsx
-- 2. For each plant and zone combination, apply the climate-to-adjustment mapping
-- 3. Insert all 200 rows (20 plants x 10 zones)
