import type { MonthPlantingGuide, PlantingMonth } from './types'

export type PlantingClimateKey = 'cold' | 'cool' | 'temperate' | 'warm' | 'tropical'

/** Month sow/plant lists keyed by growing climate (canonical matrix). Source: data/drafts/planting-from-claude.json */
export const PLANTING_BY_CLIMATE: Record<
  PlantingClimateKey,
  Record<PlantingMonth, MonthPlantingGuide>
> = {
  cold: {
    January: { sow: ["Carrots","Beetroot","Lettuce","Radish","Spring Onions"], plant: ["Tomatoes (protected)","Leeks","Celery"] },
    February: { sow: ["Carrots","Beetroot","Lettuce","Asian Greens","English Spinach","Radish","Fennel"], plant: ["Leeks","Silverbeet"] },
    March: { sow: ["Broad Beans","Peas","English Spinach","Spring Onions","Fennel"], plant: ["Garlic","Shallots","Cabbage","Winter Cabbage"] },
    April: { sow: ["Broad Beans","English Spinach"], plant: ["Garlic","Shallots","Onions"] },
    May: { sow: ["Broad Beans"], plant: ["Garlic","Rhubarb"] },
    June: { sow: [], plant: ["Rhubarb","Asparagus","Globe Artichoke"] },
    July: { sow: [], plant: ["Asparagus","Rhubarb","Jerusalem Artichokes","Globe Artichoke"] },
    August: { sow: ["Peas","Lettuce","Parsnips","Celeriac"], plant: ["Early Potatoes","Asparagus","Jerusalem Artichokes","Globe Artichoke"] },
    September: { sow: ["Peas","Early Carrots","Lettuce","Spring Onions","Parsnips","Broccoli","Cauliflower","Cabbage","Tomatoes (indoors)","Celeriac","Fennel"], plant: ["Early Potatoes","Onions","Garlic"] },
    October: { sow: ["Carrots","Beetroot","Lettuce","Peas","Kale","Kohlrabi","Broccoli","Cauliflower","Cabbage","Brussels Sprouts","Fennel"], plant: ["Potatoes","Tomatoes (protected)","Broccoli","Cauliflower","Celeriac"] },
    November: { sow: ["Beans","Carrots","Beetroot","Lettuce","Zucchini","Radish","Basil"], plant: ["Tomatoes (protected)","Zucchini","Leeks","Brussels Sprouts","Celery","Celeriac","Capsicum (protected)","Basil"] },
    December: { sow: ["Beans","Carrots","Lettuce","Beetroot","Spring Onions","Radish","Basil"], plant: ["Tomatoes (protected)","Leeks","Zucchini","Basil"] },
  },
  cool: {
    January: { sow: ["Beans","Carrots","Beetroot","Lettuce","Radish","Spring Onions"], plant: ["Tomatoes","Leeks","Celery","Silverbeet"] },
    February: { sow: ["Carrots","Beetroot","Lettuce","Asian Greens","English Spinach","Turnip","Swede","Radish","Fennel"], plant: ["Leeks","Brassicas","Celery","Kale"] },
    March: { sow: ["Peas","Broad Beans","English Spinach","Asian Greens","Spring Onions","Swede","Turnip","Fennel"], plant: ["Brassicas","Leeks","Cabbage","Winter Cabbage"] },
    April: { sow: ["Broad Beans","Peas","English Spinach","Spring Onions","Fennel"], plant: ["Garlic","Shallots","Onions"] },
    May: { sow: ["Broad Beans","English Spinach","Asian Greens"], plant: ["Garlic","Shallots","Kale","Leeks"] },
    June: { sow: ["Broad Beans","Peas"], plant: ["Garlic","Rhubarb","Globe Artichoke"] },
    July: { sow: ["Broad Beans","Peas"], plant: ["Asparagus","Rhubarb","Jerusalem Artichokes","Globe Artichoke"] },
    August: { sow: ["Early Peas","Broad Beans","Lettuce","Spring Onions","Parsnips","Onions","Celeriac"], plant: ["Early Potatoes","Asparagus","Jerusalem Artichokes","Rhubarb","Globe Artichoke"] },
    September: { sow: ["Peas","Early Carrots","Beetroot","Lettuce","Spring Onions","Parsnips","Broccoli","Cauliflower","Brussels Sprouts","Tomatoes (indoors)","Celeriac","Fennel"], plant: ["Early Potatoes","Onions","Potatoes"] },
    October: { sow: ["Beans","Carrots","Beetroot","Lettuce","Peas","Zucchini","Pumpkin","Kohlrabi","Kale","Fennel"], plant: ["Tomatoes (protected)","Potatoes","Broccoli","Cauliflower","Brussels Sprouts","Celery","Celeriac"] },
    November: { sow: ["Beans","Carrots","Beetroot","Lettuce","Zucchini","Pumpkin","Sweet Corn","Radish","Basil"], plant: ["Tomatoes","Zucchini","Pumpkin","Capsicum (protected)","Leeks","Brussels Sprouts","Celeriac","Basil"] },
    December: { sow: ["Beans","Carrots","Lettuce","Beetroot","Spring Onions","Radish","Basil"], plant: ["Tomatoes","Zucchini","Leeks","Celery","Sweet Corn","Basil"] },
  },
  temperate: {
    January: { sow: ["Beans","Sweet Corn","Carrots","Beetroot","Lettuce","Radish","Spring Onions","Basil"], plant: ["Tomatoes","Capsicum","Eggplant","Cucumbers","Zucchini","Sweet Corn","Basil"] },
    February: { sow: ["Carrots","Beetroot","Asian Greens","Lettuce","Radish","Spring Onions","Basil","Fennel"], plant: ["Capsicum","Eggplant","Silverbeet","Leeks","Basil"] },
    March: { sow: ["Carrots","Beetroot","Peas","Asian Greens","Lettuce","Spinach","English Spinach","Spring Onions","Radish","Fennel"], plant: ["Brassicas","Leeks","Silverbeet","Onions"] },
    April: { sow: ["Broad Beans","Peas","Carrots","Beetroot","Asian Greens","Lettuce","English Spinach","Spring Onions","Radish","Fennel"], plant: ["Garlic","Shallots","Onions","Brassicas"] },
    May: { sow: ["Broad Beans","Peas","English Spinach","Asian Greens","Onions","Spring Onions"], plant: ["Garlic","Shallots","Onions","Strawberries"] },
    June: { sow: ["Broad Beans","Peas","Onions","Radish","English Spinach"], plant: ["Garlic","Rhubarb","Asparagus","Globe Artichoke"] },
    July: { sow: ["Peas","Broad Beans","Lettuce","Spring Onions","Onions"], plant: ["Asparagus","Rhubarb","Jerusalem Artichokes","Globe Artichoke"] },
    August: { sow: ["Tomatoes (indoors)","Peas","Lettuce","Carrots","Spring Onions","Parsnips","Onions","Celeriac"], plant: ["Potatoes","Asparagus","Rhubarb","Globe Artichoke"] },
    September: { sow: ["Tomatoes","Beans","Carrots","Beetroot","Lettuce","Peas","Zucchini","Broccoli","Cauliflower","Spring Onions","Celeriac","Fennel"], plant: ["Tomatoes (protected)","Potatoes","Onions","Broccoli","Cauliflower"] },
    October: { sow: ["Beans","Sweet Corn","Cucumbers","Zucchini","Pumpkin","Carrots","Beetroot","Lettuce","Basil","Sweet Potato","Fennel"], plant: ["Tomatoes","Capsicum","Eggplant","Zucchini","Cucumbers","Potatoes","Basil","Sweet Potato","Celeriac"] },
    November: { sow: ["Beans","Sweet Corn","Cucumbers","Zucchini","Pumpkin","Lettuce","Beetroot","Spring Onions","Basil","Okra","Sweet Potato"], plant: ["Tomatoes","Capsicum","Eggplant","Zucchini","Cucumbers","Leeks","Basil","Okra","Sweet Potato","Celeriac"] },
    December: { sow: ["Beans","Sweet Corn","Carrots","Lettuce","Radish","Spring Onions","Basil","Okra","Sweet Potato"], plant: ["Tomatoes","Capsicum","Eggplant","Sweet Corn","Leeks","Silverbeet","Basil","Okra","Sweet Potato"] },
  },
  warm: {
    January: { sow: ["Beans","Sweet Corn","Cucumbers","Zucchini","Lettuce","Spring Onions","Basil","Okra"], plant: ["Eggplant","Capsicum","Sweet Potato","Zucchini","Cucumbers","Basil","Okra"] },
    February: { sow: ["Beans","Carrots","Beetroot","Asian Greens","Lettuce","Spring Onions","Basil","Okra","Fennel"], plant: ["Capsicum","Eggplant","Sweet Potato","Silverbeet","Basil","Okra"] },
    March: { sow: ["Carrots","Beetroot","Asian Greens","Lettuce","Peas","Broccoli","Cauliflower","Radish","Fennel","Celeriac"], plant: ["Leeks","Onions","Silverbeet","Brassicas"] },
    April: { sow: ["Peas","Broad Beans","Carrots","Beetroot","Asian Greens","Lettuce","English Spinach","Radish","Spring Onions","Fennel"], plant: ["Garlic","Onions","Brassicas","Broccoli","Cauliflower","Celeriac"] },
    May: { sow: ["Broad Beans","Peas","Carrots","Beetroot","Onions","English Spinach","Asian Greens","Radish"], plant: ["Garlic","Onions","Strawberries","Broccoli","Cauliflower"] },
    June: { sow: ["Broad Beans","Peas","Carrots","Beetroot","Onions","Radish","English Spinach"], plant: ["Garlic","Onions","Asparagus","Rhubarb","Globe Artichoke"] },
    July: { sow: ["Peas","Broad Beans","Lettuce","Carrots","Spring Onions","Onions"], plant: ["Asparagus","Rhubarb","Potatoes","Onions","Globe Artichoke"] },
    August: { sow: ["Tomatoes (indoors)","Peas","Lettuce","Carrots","Beetroot","Spring Onions","Onions"], plant: ["Potatoes","Asparagus","Tomatoes (protected)","Onions","Globe Artichoke"] },
    September: { sow: ["Tomatoes","Beans","Carrots","Beetroot","Lettuce","Zucchini","Cucumbers","Spring Onions","Fennel"], plant: ["Tomatoes","Potatoes","Zucchini","Capsicum","Eggplant"] },
    October: { sow: ["Beans","Sweet Corn","Cucumbers","Zucchini","Pumpkin","Carrots","Lettuce","Beetroot","Basil","Okra","Fennel"], plant: ["Tomatoes","Capsicum","Eggplant","Zucchini","Sweet Potato","Cucumbers","Basil","Okra"] },
    November: { sow: ["Beans","Sweet Corn","Cucumbers","Zucchini","Lettuce","Spring Onions","Basil","Okra"], plant: ["Eggplant","Capsicum","Sweet Potato","Zucchini","Leeks","Basil","Okra"] },
    December: { sow: ["Beans","Sweet Corn","Cucumbers","Lettuce","Spring Onions","Radish"], plant: ["Eggplant","Capsicum","Sweet Potato","Cucumbers","Silverbeet"] },
  },
  tropical: {
    January: { sow: ["Asian Greens","Silverbeet","Spring Onions"], plant: ["Sweet Potato","Silverbeet"] },
    February: { sow: ["Asian Greens","Sweet Corn","Spring Onions"], plant: ["Sweet Potato","Silverbeet"] },
    March: { sow: ["Beans","Asian Greens","Lettuce","Tomatoes","Capsicum","Basil","Okra"], plant: ["Eggplant","Sweet Potato","Basil","Okra"] },
    April: { sow: ["Tomatoes","Capsicum","Eggplant","Asian Greens","Lettuce","Carrots","Beetroot","Basil","Okra"], plant: ["Eggplant","Sweet Potato","Tomatoes","Basil","Okra"] },
    May: { sow: ["Carrots","Beetroot","Asian Greens","Lettuce","Beans","Radish","Spring Onions","Basil","Okra"], plant: ["Tomatoes","Capsicum","Eggplant","Basil","Okra"] },
    June: { sow: ["Carrots","Beetroot","Peas","Asian Greens","Lettuce","Radish","Spring Onions","Onions"], plant: ["Tomatoes","Capsicum","Brassicas"] },
    July: { sow: ["Carrots","Beetroot","Peas","Asian Greens","Lettuce","Beans","Radish","Onions"], plant: ["Tomatoes","Capsicum","Sweet Potato","Eggplant"] },
    August: { sow: ["Beans","Sweet Corn","Asian Greens","Lettuce","Pumpkin","Cucumbers","Spring Onions"], plant: ["Sweet Potato","Tomatoes","Capsicum"] },
    September: { sow: ["Beans","Sweet Corn","Cucumbers","Pumpkin","Asian Greens","Lettuce","Spring Onions"], plant: ["Sweet Potato","Eggplant","Cucumbers"] },
    October: { sow: ["Beans","Sweet Corn","Cucumbers","Asian Greens","Lettuce","Spring Onions"], plant: ["Sweet Potato","Capsicum","Eggplant"] },
    November: { sow: ["Beans","Asian Greens","Sweet Corn","Spring Onions"], plant: ["Sweet Potato","Silverbeet"] },
    December: { sow: ["Beans","Asian Greens","Spring Onions"], plant: ["Sweet Potato","Silverbeet"] },
  },
}
