import type { SouthernSeason } from '@/lib/seasonDisplay'

/** Fourteen unique dashboard week lines per season (cold climate, southern AU). */
export const COLD_WEEK_LINES: Record<
  SouthernSeason,
  readonly [
    string, string, string, string, string, string, string, string,
    string, string, string, string, string, string,
  ]
> = {
  Summer: [
    'Early summer: harvest often and water deeply on warm days while young fruit and greens are still tender.',
    'Keep leafy crops and roots productive; mulch exposed beds before dry, windy spells.',
    'Succession sow quick greens and herbs where space opens after harvests.',
    'Watch wind-exposed beds; stake climbers and water in the morning on hot days.',
    'Late summer shift: clear tired crops and refresh mulch before autumn planting.',
    'Sow last quick greens and prepare space for brassicas as evenings begin to cool.',
    'Plan autumn beds: compost empty spots and order garlic and onion sets if needed.',
    'Harvest remaining tender crops at peak quality before cooler nights return.',
    'Start clearing summer crops that are finished; avoid leaving pest habitat in spent plants.',
    'Check soil moisture under mulch; coastal sites can dry out between light rain events.',
    'Final summer pickings: beans, berries, and leafy greens before you reset beds for autumn.',
    'Close the summer crop cycle: tidy beds, save seed if useful, and note what thrived in your microclimate.',
    'Summer runs long in the calendar: keep harvesting, refresh mulch, and clear spent crops before autumn planting crowds the schedule.',
    'Final summer beat: protect exposed beds from wind, note disease on tired foliage, and line up garlic and green-manure beds.',
  ],
  Autumn: [
    'Autumn opens: prioritise garlic, onions, and frost-hardy greens while soil still holds warmth.',
    'Plant brassicas and legumes for winter harvest; keep seedlings watered as they establish.',
    'Garlic and shallots go in now on many sites; mulch after planting to steady soil temperature.',
    'Harvest tender crops at peak ripeness as nights begin to cool.',
    'Growth stays steady in early autumn; watch forecasts and cover tender crops on cold nights.',
    'Coastal gardens often stay mild a little longer; favour hardy greens over rushed tender plant-outs.',
    'Evenings are cooling; keep frost cloth handy and finish planting winter staples.',
    'Autumn is advancing; protect tender crops on cold nights and avoid inland planting dates on the coast.',
    'Growth is slowing; finish remaining planting while soil still has warmth and ease back on watering.',
    'Delay dormant pruning until deciduous trees have actually dropped leaves in your garden.',
    'Late autumn: frosts may arrive later on the coast; favour frost-hardy vegetables and keep covers ready.',
    'Close out autumn with hardy plantings in the ground and tender crops cleared or protected.',
    'Autumn is stretching on: finish garlic and onion planting while soil still accepts a dibber, and keep covers handy for surprise cold.',
    'Last autumn window: clear summer debris, firm up drainage before winter rain, and favour only frost-hardy plant-outs.',
  ],
  Winter: [
    'Winter begins quietly: maintain covers, improve soil on empty beds, and plan spring rotations.',
    'Check overwintering brassicas and greens; water only when soil is dry under mulch.',
    'Order seeds and plan bed layout while growth is slow.',
    'Improve drainage on wet pockets and add compost to beds you will use first in spring.',
    'Midwinter: prune deciduous fruit only once fully dormant; protect grafts and young bark.',
    'Coastal trees may still hold leaves; wait for true dormancy before hard pruning.',
    'Start slow crops indoors or under cover: onions, leafy greens, and early brassicas.',
    'Clean and prepare propagation space; check stored seed viability.',
    'Late winter: soil may stay cold, so protected sowing beats rushing tender crops outdoors.',
    'Prepare spring beds when workable; last chance for bare-root tree planting in many areas.',
    'Harden off early seedlings gradually as days lengthen.',
    'Spring is approaching: finalise seed orders and repair supports before the rush.',
    'Winter lingers: avoid heavy digging until structure is friable, check stakes on overwintered greens, and stage seed trays where they get light.',
    'Late winter beat: sharpen tools, test soil in spring beds, and hold tender sowings until nights consistently ease.',
  ],
  Spring: [
    'Soil warms slowly: start seeds under cover and delay tender transplants until nights settle.',
    'Direct sow peas, broad beans, and hardy greens where soil is workable.',
    'Harden off seedlings on mild days; keep cover ready for late frosts on clear nights.',
    'Finish bed prep with compost; avoid working soil when waterlogged.',
    'Harden off cool-season seedlings and sow peas and broad beans in open ground.',
    'Plant potatoes and onions; keep frost protection for unexpected cold snaps.',
    'Transplant hardy brassicas and stake peas; scout for snails on new growth.',
    'Core spring window: potatoes and hardy greens lead; tender crops stay under cover.',
    'Transplant hardy crops and stake climbers; watch for late frosts after warm days.',
    'Plant summer crops under cover; increase watering as growth accelerates.',
    'Late spring is brief: plant tomatoes and beans in protected spots until frost risk drops.',
    'Remove frost protection only after a run of settled mild nights; feed actively growing crops lightly.',
    'Spring runs long in the calendar: keep hardening off in stages and delay outdoor tomatoes until your site has settled.',
    'Final spring beat: expand summer plantings, scout aphids on soft growth, and store frost cloth dry for next season.',
  ],
}
