import type { SouthernSeason } from '@/lib/seasonDisplay'

/** Fourteen unique dashboard week lines per season (cool climate, southern AU). */
export const COOL_WEEK_LINES: Record<
  SouthernSeason,
  readonly [
    string, string, string, string, string, string, string, string,
    string, string, string, string, string, string,
  ]
> = {
  Summer: [
    'Early summer: harvest regularly and water deeply before heat and dry winds stress plants.',
    'Keep fruiting crops picked to extend production; mulch to hold moisture.',
    'Succession sow lettuce, herbs, and quick greens in partial shade where possible.',
    'Stake tomatoes and beans; maintain airflow around dense foliage.',
    'Shift beds toward autumn: sow brassicas in trays if you start them under cover.',
    'Clear struggling summer crops and refresh compost on empty beds.',
    'Plant leeks and late brassicas where space allows; water new seedlings consistently.',
    'Harvest corn, zucchini, and tomatoes at peak ripeness.',
    'Prepare garlic beds and green manure patches for autumn planting.',
    'Reduce feeding on woody plants as growth slows toward autumn.',
    'Last summer sowings of greens and herbs for autumn picking.',
    'Tidy the garden: note pest issues and plan crop rotation for next season.',
    'Extra late summer: keep picking fruiting crops and refresh mulch before autumn rain and cooler nights.',
    'Summer tail: clear pest-heavy plants, compost empty beds, and queue garlic and green-manure sowings.',
  ],
  Autumn: [
    'Autumn planting peaks: garlic, onions, and brassicas while soil is still warm enough.',
    'Sow peas and broad beans; mulch new plantings to reduce weed competition.',
    'Plant green manure on empty beds you will rest over winter.',
    'Harvest remaining summer crops before quality drops in cooler weather.',
    'Cover tender plants on cold nights; sheltered sites may still see useful growth.',
    'Favour hardy greens and root crops as growth rate eases.',
    'Finish planting alliums and brassicas; check for slugs around new seedlings.',
    'Ease watering as evaporation drops; keep soil moist for establishing plants.',
    'Growth is slowing: complete planting plans and ease back on nitrogen on woody plants.',
    'Prune only when trees are dormant and leaves have fully fallen.',
    'Protect tender crops when forecasts dip; harvest at peak ripeness before frosts.',
    'Close autumn with beds mulched and tender summer crops cleared.',
    'Autumn is stretching on: tuck in last alliums, check drainage, and keep frost cloth where tender crops remain.',
    'Last autumn beat: harvest at peak quality, avoid heavy digging on wet soil, and favour hardy greens only.',
  ],
  Winter: [
    'Winter maintenance: check covers, plan spring, and improve soil when beds are empty.',
    'Harvest winter greens steadily to encourage continued leaf production.',
    'Prune deciduous fruit in calm weather once fully dormant.',
    'Order seeds and plan succession for spring.',
    'Midwinter: minimal outdoor planting; focus on compost and tool maintenance.',
    'Start seedlings indoors for early spring transplanting.',
    'Check stakes and netting before spring growth begins.',
    'Improve wet beds with compost; avoid compacting sodden soil.',
    'Late winter sowing under cover: tomatoes, peppers, and early brassicas.',
    'Prepare potato beds and lime if soil tests suggest it.',
    'Harden off seedlings gradually as frost risk slowly eases.',
    'Finalise spring layout and crop rotation before the busy season.',
    'Winter lingers: service tools, order any missing seed, and ventilate covered greens on mild days.',
    'Late winter beat: prepare potato trenches and lime only where tests call for it; keep tender sowings under cover.',
  ],
  Spring: [
    'Spring starts cautiously: seeds under cover, frost cloth ready for clear cold nights.',
    'Direct sow peas, potatoes, and hardy greens in workable soil.',
    'Plant asparagus and rhubarb crowns if you have them on order.',
    'Harden off seedlings on mild afternoons; bring under cover overnight.',
    'Sow carrots, beetroot, and leafy greens; thin seedlings for airflow.',
    'Plant potatoes and transplant hardy brassicas.',
    'Begin tomato and capsicum under cover; do not rush outdoor plant-out.',
    'Transplant seedlings as soil warms; feed lightly with balanced fertiliser.',
    'Plant tomatoes under cover; stake early and mulch when soil is warm.',
    'Increase watering as growth speeds up; scout for aphids on soft growth.',
    'Plant beans and zucchini in protected spots until frost risk is low.',
    'Expand summer plantings as nights settle; remove covers in stages.',
    'Spring runs long in the calendar: stagger tomato plant-out and keep beans and zucchini protected until frost risk fades.',
    'Final spring beat: stake climbers early, mulch warm beds, and dry-store frost covers for next winter.',
  ],
}
