import type { SouthernSeason } from '@/lib/seasonDisplay'

/** Fourteen unique dashboard week lines per season (temperate / coastal AU). */
export const TEMPERATE_WEEK_LINES: Record<
  SouthernSeason,
  readonly [
    string, string, string, string, string, string, string, string,
    string, string, string, string, string, string,
  ]
> = {
  Summer: [
    'Peak summer: water fruiting crops early, mulch well, and harvest before heat and humidity peak.',
    'Pick beans, tomatoes, and zucchini regularly to keep plants productive through warm spells.',
    'Shade young seedlings on hot afternoons and check containers daily on windy coastal sites.',
    'Watch for mildew when humidity rises; improve airflow around dense tomato and bean foliage.',
    'Refresh tired beds with compost and sow quick greens in spots that catch afternoon shade.',
    'Plan autumn brassicas; start seedlings under cover if direct sowing is risky in heat.',
    'Water deeply at the root zone; avoid light sprinkling that encourages shallow roots.',
    'Harvest corn and stone fruit at peak ripeness; net trees if birds are active.',
    'Ease feeding on woody plants as growth slows; keep steady moisture on establishing crops.',
    'Late summer: clear pest-heavy plants and make space for garlic and green-manure patches.',
    'Succession sow lettuce and herbs where soil stays cool; mulch before dry, windy weeks.',
    'Tidy structures and note crop rotation before autumn planting ramps up.',
    'Coastal summer tail: harvest at dawn, mulch containers, and queue autumn brassica trays.',
    'Final summer beat: compost spent crops and protect remaining fruit from sun scald after heat spikes.',
  ],
  Autumn: [
    'Autumn begins: sow brassicas and collect fallen leaves for compost while soil still holds warmth.',
    'Plant garlic and onions in well-drained rows; mulch lightly after watering in.',
    'Sow peas and broad beans; keep seedlings moist as nights cool.',
    'Harvest remaining summer crops before quality drops in cooler, wetter spells.',
    'Cover tender plants when forecasts dip; coastal sites may still see useful growth.',
    'Adjust watering as evaporation drops; favour hardy greens over rushed tender plant-outs.',
    'Finish brassica planting; check for slugs around new seedlings after rain.',
    'Green manure empty beds you will rest over winter.',
    'Growth is slowing: complete planting plans and ease back on nitrogen on woody plants.',
    'Prune only when trees are dormant; wait until leaves have fallen on deciduous fruit.',
    'Protect late tender crops when cold snaps threaten; harvest at peak ripeness.',
    'Close autumn with beds mulched and drainage clear before winter rain.',
    'Extended autumn: tuck in last alliums and ventilate covered greens on mild days.',
    'Last autumn beat: avoid heavy digging on wet soil; favour hardy greens and root crops only.',
  ],
  Winter: [
    'Winter care: maintain citrus and leafy greens with lighter feeding while growth is slower.',
    'Harvest winter greens steadily to encourage continued leaf production.',
    'Prune deciduous fruit on calm days once fully dormant.',
    'Order seeds and plan succession for spring.',
    'Midwinter: focus on compost, tool maintenance, and improving wet beds when workable.',
    'Start tomatoes and capsicum indoors for early spring transplanting.',
    'Check stakes and netting before spring growth begins.',
    'Improve drainage and bed structure with compost; keep heavy foot traffic off soft soil.',
    'Late winter sowing under cover: early brassicas and hardy greens outdoors where frost is mild.',
    'Prepare potato beds; lime only if soil tests suggest it.',
    'Harden off seedlings gradually as frost risk slowly eases on coastal sites.',
    'Finalise spring layout and crop rotation before the busy season.',
    'Winter lingers: service tools and ventilate covered greens on mild, dry afternoons.',
    'Late winter beat: prepare potato trenches and keep tender sowings under cover until soil warms.',
  ],
  Spring: [
    'Spring opens: watch overnight lows and stagger warm-season planting until soil is ready.',
    'Direct sow peas, potatoes, and hardy greens in workable soil.',
    'Plant asparagus and rhubarb crowns if you have them on order.',
    'Harden off seedlings on mild afternoons; bring under cover overnight.',
    'Sow carrots, beetroot, and leafy greens; thin seedlings for airflow.',
    'Transplant hardy brassicas; begin tomatoes and capsicum under cover.',
    'Plant beans and zucchini in protected spots until frost risk is low.',
    'Increase watering as growth speeds up; scout for aphids on soft new growth.',
    'Plant summer staples with stakes ready for tomatoes, capsicum, and cucumbers.',
    'Mulch warm beds and expand summer plantings as nights settle.',
    'Feed lightly with balanced fertiliser on actively growing crops.',
    'Remove covers in stages as frost risk fades; keep cloth ready for late cold snaps.',
    'Long spring: stagger tomato plant-out and protect beans until nights are reliably mild.',
    'Final spring beat: stake climbers early and dry-store frost covers for next winter.',
  ],
}
