import type { SouthernSeason } from '@/lib/seasonDisplay'

/** Fourteen unique dashboard week lines per season (warm subtropical AU). */
export const WARM_WEEK_LINES: Record<
  SouthernSeason,
  readonly [
    string, string, string, string, string, string, string, string,
    string, string, string, string, string, string,
  ]
> = {
  Summer: [
    'Summer peak: water deeply at dawn, mulch thickly, and harvest in the cooler part of the day.',
    'Maintain mulch and watch for fruit fly on ripening stone fruit and tomatoes.',
    'Shade sensitive crops during heat spikes; containers dry out first.',
    'Pick regularly to keep beans, zucchini, and capsicum producing through humid spells.',
    'Improve airflow when mildew appears after rain; avoid overhead watering at night.',
    'Succession sow quick greens in partial shade where summer crops are finishing.',
    'Refresh tired beds with compost before planning autumn or dry-season crops.',
    'Feed fruiting crops lightly; hold nitrogen on woody plants in extreme heat.',
    'Storm prep: secure stakes and harvest before heavy rain if humidity builds.',
    'Late summer: shift toward heat-tolerant greens and recovery crops on emptied beds.',
    'Reduce new plantings in exposed beds; focus water on crops already fruiting.',
    'Note pest pressure and plan rotation before autumn planting windows open.',
    'Warm summer tail: deep water citrus and mulch containers before dry, windy weeks.',
    'Final summer beat: clear diseased foliage and queue shade cloth for the next heatwave.',
  ],
  Autumn: [
    'Autumn still productive: sow quick greens and refresh summer beds while conditions allow.',
    'Harvest remaining heat lovers before quality drops in cooler nights.',
    'Improve airflow and harvest before storms if humidity rises.',
    'Plant peas and leafy greens; mulch new rows after watering in.',
    'Ease watering as evaporation drops; watch for snails in damp beds.',
    'Shift toward dry-season favourites where your climate dries in winter.',
    'Reduce water on dormant summer crops; keep moisture on establishing greens.',
    'Compost spent summer plants and prepare beds for winter planting.',
    'Light feeding supports steady growth on leafy crops in mild conditions.',
    'Protect tender crops if an unseasonal cold snap arrives.',
    'Finish autumn sowing of hardy greens and herbs.',
    'Close autumn with beds mulched and tools serviced.',
    'Extended autumn: succession sow Asian greens and legumes while soil stays warm.',
    'Last autumn beat: harvest at peak and favour quick crops over long-season tender plant-outs.',
  ],
  Winter: [
    'Mild winter: peas, greens, and citrus maintenance suit steady growth in many warm areas.',
    'Harvest winter greens regularly to encourage continued leaf production.',
    'Light feeding can support leafy crops; watch for aphids on soft growth.',
    'Prune citrus lightly and check for scale on leaves and stems.',
    'Order seeds and plan spring layout while growth is slower.',
    'Improve bed structure with compost and avoid heavy traffic when soil is soft.',
    'Start tomatoes and beans under cover for early spring transplanting.',
    'Prepare potato beds and check irrigation before spring demand rises.',
    'Harden off seedlings on mild afternoons; protect from brief cold snaps.',
    'Mulch to hold moisture on establishing crops through dry winter weeks.',
    'Begin spring prep as soil warms; sow heat lovers where frost risk is low.',
    'Finalise crop rotation and bed layout before the busy season.',
    'Winter lingers: ventilate covered greens on mild days and check snail traps after rain.',
    'Late winter beat: transplant hardy crops first and hold tender summer crops under cover.',
  ],
  Spring: [
    'Spring warmth: sow heat-lovers early in warm soil, but watch for brief cool snaps.',
    'Transplant tomatoes, capsicum, and beans with a strong mulch layer.',
    'Stake climbers early and improve airflow before humidity builds.',
    'Build shade structures before peak heat; water new transplants consistently.',
    'Sow corn, beans, and cucurbits in protected spots until nights settle.',
    'Increase feeding as growth accelerates; scout for fruit fly on young fruit.',
    'Expand summer plantings; keep frost cloth ready for late cold nights.',
    'Mulch warm beds and harvest greens before they bolt in lengthening days.',
    'Plant sweet potato slips and perennial herbs where frost risk is low.',
    'Maintain steady irrigation as temperatures climb.',
    'Thin crowded seedlings for airflow; net fruit where birds are active.',
    'Remove covers in stages as frost risk fades.',
    'Long spring: stagger plant-out of tender crops and keep mulch topped up.',
    'Final spring beat: secure stakes and set irrigation before the first sustained heat.',
  ],
}
