-- Seed script: Populate plant_timelines table with 89 plants across 8 Australian hardiness zones
-- Zones: 8a (cool), 8b-9a (temperate), 9b-12b (warm)
-- Total records: 89 plants × 8 zones = 712 plant timeline entries

-- Clear existing data (optional - comment out if you want to preserve existing records)
-- DELETE FROM plant_timelines;

-- Helper: Insert plant for all zones with appropriate climate multipliers
-- Usage: CALL seed_plant(name, sow, seedling, harvest, warm_mult, cool_mult, temperate_mult, care_array, activities_json)

-- Tomatoes: 8a(cool 1.2), 8b-9a(temperate 1.0), 9b-12b(warm 0.9)
INSERT INTO plant_timelines (plant_name, au_hardiness_zone, sow_to_seedling, seedling_to_harvest, harvest_window, growth_multiplier, watering_frequency, extra_care, key_activities)
VALUES
('Tomatoes', '8a', 21, 60, 45, 1.2, 4, '{"Use frost protection when needed","Monitor night temperatures"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '8b', 21, 60, 45, 1.05, 3, '{"Monitor frost dates","Use season extenders"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '9a', 21, 60, 45, 1.0, 3, '{}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '9b', 21, 60, 45, 0.95, 2, '{"Provide afternoon shade","Monitor for blossom end rot"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '10a', 21, 60, 45, 0.9, 2, '{"Provide afternoon shade","Monitor for blossom end rot"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '10b', 21, 60, 45, 0.85, 2, '{"Provide afternoon shade","Monitor for blossom end rot"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '11a', 21, 60, 45, 0.8, 2, '{"Shade cloth often needed","Monitor for heat stress"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb),
('Tomatoes', '12b', 21, 60, 45, 0.75, 2, '{"Year-round growing potential","Shade critical for many crops"}', '[{"timing":21,"activity":"Fertilise","details":"Use balanced 5-5-5 organic fertilizer, apply 2 tablespoons per plant in a ring 4 inches from stem. Water thoroughly after application to avoid root burn.","category":"fertilizing"},{"timing":28,"activity":"Monitor for pests","details":"Check undersides of leaves daily for hornworms (green with white stripes, up to 4 inches long) and aphids (small, clustered). Look for holes or stippled yellow damage. Hand-pick hornworms or use Bt spray. For aphids, spray with neem oil or insecticidal soap every 7 days as needed.","category":"pest"},{"timing":35,"activity":"Install supports","details":"Place cage (at least 5-6 feet tall) or drive 6-foot wooden stakes 8 inches into ground, 4 inches from stem base. Use soft ties (cloth strips or horticultural tape) to loosely tie stems every 12 inches as plant grows. Stakes must support 20-30 pounds of fruit.","category":"planting"},{"timing":45,"activity":"Remove suckers and lower leaves","details":"Remove side shoots (suckers) growing in crotch between main stem and branches to direct energy to fruit. Remove all leaves touching ground or within 12 inches of soil to improve air circulation and reduce disease.","category":"pruning"},{"timing":60,"activity":"Check first fruits for ripeness","details":"Fruits are ready when they reach full color for variety (deep red, orange, pink, or yellow depending on type) and feel slightly soft to gentle pressure. Pick in morning when cool. Fully ripe tomatoes develop best flavor.","category":"harvest"}]'::jsonb);

-- Note: This is a template showing Tomatoes across all 8 zones
-- For full 89 plants × 8 zones = 712 records, use the TypeScript seed script:
-- npx ts-node scripts/seed-plants-to-supabase.ts
--
-- This SQL file demonstrates the structure for manual setup or incremental inserts

-- Index for performance (if not already created)
CREATE INDEX IF NOT EXISTS idx_plant_timelines_zone ON plant_timelines(au_hardiness_zone);
CREATE INDEX IF NOT EXISTS idx_plant_timelines_name ON plant_timelines(plant_name);
CREATE INDEX IF NOT EXISTS idx_plant_timelines_composite ON plant_timelines(plant_name, au_hardiness_zone);

-- Done
SELECT COUNT(*) as total_records FROM plant_timelines;
